ktor:
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "org.kotlined.cc.app.ktor.ApplicationKt.module"

contactcenter:
  repository:
    test: "inmemory"
    prod: "$DB_TYPE_PROD:inmemory"

    cassandra:
      hosts: localhost
      keyspace: test_keyspace
      pass: cassandra
      port: 9042
      user: cassandra
